cocoa/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic.base import RedirectView
from rest_framework import routers
from django.conf.urls.static import static
from django.conf import settings

from programming.api import EventViewSet
from registration.api import AttendeeViewSet, VolunteerViewSet
from website.api import TagViewSet, UserViewSet

admin.autodiscover()

router = routers.DefaultRouter()
router.register(r"events", EventViewSet, basename="events")
router.register(r"volunteers", VolunteerViewSet)
router.register(r"attendees", AttendeeViewSet)
router.register(r"user", UserViewSet, basename="user")
router.register(r"tags", TagViewSet, basename="tags")

urlpatterns = [
    path("favicon.ico", RedirectView.as_view(url="/static/favicon.ico", permanent=True)),
    path("api/v1/", include(router.urls)),
    path("manage/admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("programming/", include("programming.urls")),
    path("registration/", include("registration.urls")),
    path("manage/", include("website.urls")),
    path("", include("cms.urls")),
]

website/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("reports/tent_cards/", views.tent_cards, name="reports_tent_cards"),
    path("reports/door_cards/", views.door_cards, name="reports_door_cards"),
    path("reports/badge_labels/", views.badge_labels, name="reports_badge_labels"),
    path("reports/pocket_program/", views.pocket_program, name="reports_pocket_program"),
    path("reports/programbook/", views.program_book, name="reports_program_book"),
    path("reports/", views.reports_index, name="reports_index"),
    path("email/", views.email_index, name="email_index"),
]

programming/models.py
import textwrap
from datetime import timedelta

import arrow
from colorful.fields import RGBColorField
from django.db import models

from convention.models import BaseModel, Constance


class Room(BaseModel):
    """A room that an event is held in."""

    constance = models.ForeignKey(Constance, on_delete=models.CASCADE)

    name = models.CharField(
        max_length=255,
        help_text="The name of this room.",
    )

    short_name = models.CharField(
        max_length=255,
        null=True,
        blank=True,
        help_text="A shortened version of this room's name, suitable for badge labels.",
    )

    # Only currently used in the calendar field. Default to something rather neutral, that both
    # black and white text will show up on
    color = RGBColorField(default="#777777")

    important = models.BooleanField(
        default=True,
        help_text="""
    If False, this room will get collapsed into an "Other" category when space is tight.
    """.strip(),
    )

    def get_active_events(self, day=None):
        events = self.event_set.filter(
            room__isnull=False, start_time__isnull=False, visible=True
        ).order_by("start_time")

        if day:
            start, end = arrow.get(day).span("day")
            start = start.shift(hours=6)
            end = end.shift(hours=6)
            events = events.filter(start_time__gte=start.datetime, start_time__lte=end.datetime)

        return events

    def get_short_name(self):
        """Gets short name if set, otherwise gets regular name"""

        return self.short_name or self.name


class Format(BaseModel):
    """Represents the format of an event, such as Panel or Interview."""

    constance = models.ForeignKey(Constance, on_delete=models.CASCADE)

    name = models.CharField(max_length=255)

    color = RGBColorField()

    class Meta:
        ordering = ["name"]


class Category(BaseModel):
    """Represents the format of an event, such as Literary or Fannish."""

    constance = models.ForeignKey(Constance, on_delete=models.CASCADE)

    name = models.CharField(max_length=255)

    color = RGBColorField()

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Categories"


class Event(BaseModel):
    """Represents an event at the convention."""

    constance = models.ForeignKey(Constance, on_delete=models.CASCADE)

    name = models.CharField(
        max_length=255, help_text="The name of this event. Should be something short and catchy."
    )

    description = models.TextField(
        blank=True,
        default="",
        help_text="The description for this event. Can be longer and have multiple paragraphs.",
    )

    proposer = models.ForeignKey(
        "website.User",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text=textwrap.dedent(
            """
            The user that proposed this event via the public site.
            If unset, this event was added via the admin site
        """
        ),
    )

    visible = models.BooleanField(
        default=False,
        help_text="Whether or not this event will be displayed on the public site",
    )

    # Event notes. These will not be displayed publicly
    notes = models.TextField(
        blank=True,
        default="",
        help_text="Administrator notes for this event",
    )

    room = models.ForeignKey(
        Room,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="The room that this event will be held in",
    )

    start_time = models.DateTimeField(
        blank=True,
        null=True,
        help_text="When this event starts",
    )

    duration = models.IntegerField(
        default=60,
        help_text="Event duration (in minutes)",
    )

    format = models.ForeignKey(
        Format,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="The format of this event",
    )

    category = models.ForeignKey(
        Category,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        help_text="The category (or track) of this event",
    )

    participants = models.ManyToManyField(
        "registration.Attendee",
        through="Participant",
        blank=True,
        help_text="The list of participants in this event",
    )

    attendance_size = models.IntegerField(
        blank=True,
        null=True,
        help_text="""
    The number of people that attended this event. Useful for tracking historical data.
    """.strip(),
    )

    def get_end_time(self):
        """Calculates end time from start time and duration."""
        if self.start_time:
            return self.start_time + timedelta(minutes=self.duration)

    def get_room_name(self):
        if self.room:
            return self.room.name

    class Meta:
        ordering = ["name"]

    @classmethod
    def get_active(cls):
        return cls.objects.filter(
            room__isnull=False, start_time__isnull=False, visible=True
        ).order_by("start_time")


class Participant(BaseModel):
    constance = models.ForeignKey(Constance, on_delete=models.CASCADE)

    event = models.ForeignKey(
        Event,
        on_delete=models.CASCADE,
        help_text="The event this participant is associated with",
    )

    attendee = models.ForeignKey(
        "registration.Attendee",
        on_delete=models.CASCADE,
        help_text="The registered person attending this event",
    )

    is_moderator = models.BooleanField(
        default=False,
        help_text="Whether or not this participant is moderating the event",
    )

    confirmed = models.BooleanField(
        default=False,
        help_text="Whether or not this participant is actually confirmed for the event",
    )

    notes = models.TextField(
        default="",
        blank=True,
        null=False,
        help_text="Notes about this participant",
    )

    class Meta:
        ordering = ["-is_moderator", "attendee__email"]

    def __str__(self):
        return f"<Participant: {self.attendee.email} -> {self.event.name}>"

    __repr__ = __str__

website/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

from convention.models import BaseModel, Convention


class UserManager(BaseUserManager):
    def create_user(self, email, first_name, last_name, password, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)

        if not email:
            raise ValueError("An email is required for creating a user.")

        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, email, first_name, last_name, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")

        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(email, first_name, last_name, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin, BaseModel):

    convention = models.ForeignKey(Convention, on_delete=models.CASCADE)

    email = models.EmailField(verbose_name="Email address", max_length=255, unique=True)

    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)

    is_staff = models.BooleanField(
        "staff status",
        default=False,
        help_text="Designates whether the user can log into this admin site.",
    )

    is_active = models.BooleanField(
        "active",
        default=True,
        help_text="Whether this user should be treated as active."
        " Unselect this instead of deleting accounts.",
    )

    starred = models.ManyToManyField(
        "programming.Event",
        blank=True,
        related_name="starrers",
    )

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    class Meta:
        ordering = ["first_name", "last_name", "email"]
        verbose_name = "Login"
        verbose_name_plural = "Logins"

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.email})"

    def save(self, *args, **kwargs):
        try:
            self.convention
        except Convention.DoesNotExist:
            self.convention = Convention.objects.get()

        super(User, self).save(*args, **kwargs)

    def get_full_name(self):
        return f"{self.first_name} {self.last_name}"

    def get_short_name(self):
        return f"{self.first_name}"

website/forms.py
from django import forms
from django.core.exceptions import SuspiciousOperation

from convention.models import Convention
from registration.models import Attendee
from website.models import User


class SignupForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            "email",
            "first_name",
            "last_name",
        )

    def signup(self, request, user):
        convention = Convention.objects.get()
        constance = convention.current_constance()
        # Something weird is going on if they already have an attendee associated with them
        if user.attendee_set.exists():
            raise SuspiciousOperation(
                f"Somehow, the user {user} with an existing attendee set signed up!"
            )

        # Otherwise, they might have an unassociated Attendee that was manually added, so check
        # to see if one exists here.
        try:
            attendee = Attendee.objects.get(
                email=user.email,
                first_name=user.first_name,
                last_name=user.last_name,
                registrant=None,
                convention=convention,
            )
        except Attendee.DoesNotExist:
            attendee = Attendee(
                email=user.email,
                first_name=user.first_name,
                last_name=user.last_name,
                registrant=user,
                convention=convention,
            )

        attendee.save()

website/views.py
import json
from collections import OrderedDict
from itertools import groupby

import arrow
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import DateTimeField
from django.db.models.functions import Trunc
from django.shortcuts import redirect, render
from rest_framework.renderers import JSONRenderer
from taggit.models import Tag

from convention.models import Convention
from programming import api
from programming.models import Participant
from registration.models import Attendee
from website.api import TagSerializer

BADGE_LABELS_SQL = """
SELECT DISTINCT
  "registration_attendee"."id",
  "registration_attendee"."first_name",
  "registration_attendee"."last_name",
  "registration_attendee"."display_name",
  "programming_event"."start_time",
  "programming_event"."name" AS "event_name",
  "programming_room"."short_name" AS "room_name"
FROM
  "registration_attendee"
  INNER JOIN "programming_participant" ON (
    "registration_attendee"."id" = "programming_participant"."attendee_id"
  )
  INNER JOIN "programming_event" ON (
    "programming_participant"."event_id" = "programming_event"."id"
  )
  INNER JOIN "programming_room" ON (
    "programming_event"."room_id" = "programming_room"."id"
  )
WHERE
  (
    "programming_participant"."confirmed" = True
    AND "programming_event"."constance_id" = %s
    AND "programming_event"."room_id" IS NOT NULL
    AND "programming_event"."start_time" IS NOT NULL
    AND "programming_participant"."id" IS NOT NULL
  )
ORDER BY
  "registration_attendee"."first_name" ASC;
""".strip()


@staff_member_required
def reports_index(request):
    events = (
        api.EventViewSet()
        .get_queryset()
        .filter(room__isnull=False, start_time__isnull=False)
        .order_by("start_time")
    )

    events = (
        JSONRenderer()
        .render(api.EventSerializer(events, many=True, context={"request": request}).data)
        .decode("utf-8")
    )

    participant_emails = json.dumps(
        {
            f"{p.attendee.get_display_name()}": p.attendee.email
            for p in Participant.objects.select_related("attendee")
        }
    )

    return render(request, "website/reports/index.html", locals())


@staff_member_required
def email_index(request):
    return render(request, "website/email/index.html", locals())


@staff_member_required
def program_book(request):
    events = api.EventViewSet().get_queryset()

    events = (
        JSONRenderer()
        .render(api.EventSerializer(events, many=True, context={"request": request}).data)
        .decode("utf-8")
    )

    return render(request, "website/reports/program_book.html", locals())


@staff_member_required
def tent_cards(request):
    events = (
        api.EventViewSet()
        .get_queryset()
        .filter(room__isnull=False, start_time__isnull=False)
        .order_by(
            Trunc("start_time", "day", output_field=DateTimeField()).asc(),
            "room",
            "start_time",
        )
    )

    return render(request, "website/reports/tent_cards.html", {"events": events})


@staff_member_required
def door_cards(request):
    constance = Convention.objects.get().current_constance()
    events = (
        api.EventViewSet()
        .get_queryset()
        .filter(start_time__isnull=False, visible=True, room__isnull=False)
    )
    dates = sorted({e.start_time.strftime("%Y-%m-%d") for e in events})

    rooms = constance.room_set.exclude(name="Other").order_by("name")

    days = OrderedDict(
        (
            arrow.get(day),
            {
                room.name: room.get_active_events(day)
                for room in rooms
                if room.get_active_events(day).count()
            },
        )
        for day in dates
    )
    return render(request, "website/reports/door_cards.html", {"days": days})


@staff_member_required
def badge_labels(request):
    constance = Convention.objects.get().current_constance()

    attendees = Attendee.objects.raw(BADGE_LABELS_SQL, [constance.id])
    attendees = [(att, list(group)) for att, group in groupby(attendees)]

    chunked = [attendees[i : i + 8] for i in range(0, len(attendees), 8)]

    return render(request, "website/reports/badge_labels.html", {"chunked": chunked})


@staff_member_required
def pocket_program(request):
    constance = Convention.objects.get().current_constance()
    events = api.EventViewSet().get_queryset().filter(room__isnull=False, start_time__isnull=False)
    rooms = constance.room_set.all().order_by("name")
    important_ids = [str(r.id) for r in constance.room_set.filter(important=True)]

    events = (
        JSONRenderer()
        .render(api.EventSerializer(events, many=True, context={"request": request}).data)
        .decode("utf-8")
    )

    rooms_serialized = (
        JSONRenderer()
        .render(api.RoomSerializer(rooms, many=True, context={"request": request}).data)
        .decode("utf-8")
    )

    return render(request, "website/reports/pocket_program.html", locals())

website/templates/website/reports/badge_labels.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="{% static 'website/reports/badge_labels.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% for chunk in chunked %}
      <div class="page">
      {% for attendee, items in chunk %}
        <div class="label">
          <h3 class="name">{{ attendee.get_display_name }}</h3>
          <table>
            {% for item in items %}
              <tr>
                <td class="title">{{ item.event_name }}</td>
                <td class="day">{{ item.start_time|date:"D" }}</td>
                <td class="time">{{ item.start_time|date:"h:i A" }}</td>
                <td class="room">{{ item.room_name }}</td>
              </tr>
            {% endfor %}
          </table>
        </div>
      {% endfor %}
      </div>
    {% endfor %}
  </body>
</html>

website/templates/website/reports/door_cards.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="{% static 'website/reports/door_cards.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% for day, rooms in days.items %}
      {% for room, events in rooms.items %}
      <h1><span class="date">{{ day|date:"l" }}</span><span class="room">{{ room }}</span></h1>
      <table class='schedule'>
        {% for event in events %}
          <tr class="event">
            <td class="time">{{ event.start_time|date:"h:i A" }}</td>
            <td><span class="title">{{ event.name }}</span>
              <br />
              <span class="description">{{ event.description }}</span></td>
            <td class="participants">
              {% for participant in event.participant_set.all %}
                {{ participant.attendee.get_display_name }}<br />
              {% endfor %}
            </td>
          </tr>
        {% endfor %}
      </table>
      {% endfor %}
    {% endfor %}
  </body>
</html>

website/templates/website/reports/index.html
{% extends 'base.html' %}
{% load static %}


{% block js %}
<script defer type="text/javascript" src="{% static 'website/reports/index.js' %}"></script>
<script defer type="text/javascript" src="{% static 'js/lib/moment.js' %}"></script>

<script type="text/javascript">
window.events = {{ events|safe }};
window.participant_emails = {{ participant_emails|safe }};
</script>
{% endblock %}

{% block css %}
<style type="text/css">
#content button {
  margin-bottom: 0.5em;
  margin-right: 0.5em;
}

#content a:nth-of-type(1) {
  margin-left: 0;
}
</style>
{% endblock %}

{% block content %}
<h4>Click an option below to download a report</h4>
<br />
<a>
  <button id="email-report" class="btn btn-default">
    <span style="font-size: 3em;" class="glyphicon glyphicon-envelope"></span>
    <br />
    Generate Emails
  </button>
</a>
<a href="programbook/">
  <button class="btn btn-default">
    <span style="font-size: 3em;" class="glyphicon glyphicon-list-alt"></span>
    <br />
    Program Book
  </button>
</a>
<a href="tent_cards/">
  <button class="btn btn-default">
    <span style="font-size: 3em;" class="glyphicon glyphicon-chevron-up"></span>
    <br />
    Tent Cards
  </button>
</a>
<a href="door_cards/">
  <button class="btn btn-default">
    <span style="font-size: 3em;" class="glyphicon glyphicon-object-align-horizontal"></span>
    <br />
    Door Cards
  </button>
</a>
<a href="badge_labels/">
  <button class="btn btn-default">
    <span style="font-size: 3em;" class="glyphicon glyphicon glyphicon-tag"></span>
    <br />
    Badge Labels
  </button>
</a>
<a href="pocket_program/">
  <button class="btn btn-default">
    <span style="font-size: 3em;" class="glyphicon glyphicon glyphicon-th-list"></span>
    <br />
    Pocket Program
  </button>
</a>
{% endblock content %}

website/templates/website/reports/pocket_program.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <title>{{ convention.name }}</title>
  <link type="text/css" rel="stylesheet" href="{% static 'programming/index.css' %}"/>
  <link type="text/css" rel="stylesheet" href="{% static 'css/lib/fullcalendar.min.css' %}"/>
  <link type="text/css" rel="stylesheet" href="{% static 'css/lib/scheduler.min.css' %}"/>
  <link type="text/css" rel="stylesheet" href="{% static 'website/reports/pocket_program.css' %}"/>
  <link type="text/css" rel="stylesheet" href="{% static 'website/reports/pocket_program.print.css' %}" media="print"/>

  <script defer type="text/javascript" src="{% static 'js/lib/jquery.js' %}"></script>
  <script defer type="text/javascript" src="{% static 'js/lib/moment.js' %}"></script>
  <script defer type="text/javascript" src="{% static 'js/lib/moment-range.min.js' %}"></script>
  <script defer type="text/javascript" src="{% static 'js/lib/fullcalendar.min.js' %}"></script>
  <script defer type="text/javascript" src="{% static 'js/lib/scheduler.min.js' %}"></script>
  <script defer type="text/javascript" src="{% static 'website/reports/pocket_program.js' %}"></script>

  <script type="text/javascript">
    window.events = {{ events|safe }};
    window.rooms = {{ rooms_serialized|safe }};
    window.important_ids = {{ important_ids|safe }};
  </script>
</head>
<body></body>
</html>

website/templates/website/reports/program_book.html
{% load account %}
{% load static %}
{% load raven %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/bootstrap-theme.min.css' %}" rel="stylesheet" />
    <link href="{% static 'website/reports/program_book.css' %}" rel="stylesheet" />

    <script defer type="text/javascript" src="{% static 'js/lib/jquery.js' %}"></script>
    <script defer type="text/javascript" src="{% static 'js/lib/lodash.js' %}"></script>
    <script defer type="text/javascript" src="{% static 'js/lib/bootstrap.js' %}"></script>
    <script defer type="text/javascript" src="{% if debug %}{% static 'js/lib/vue.js' %}{% else %}{% static 'js/lib/vue.min.js' %}{% endif %}"></script>
    <script defer type="text/javascript" src="{% static 'js/lib/moment.js' %}"></script>
    <script defer type="text/javascript" src="{% static 'website/reports/program_book.js' %}"></script>
    <script type="text/javascript">window.events = {{ events|safe }};</script>
  </head>
  <body>
    <div id="content" v-cloak>
      <div id="header">
        <p>TIP: This will print better when scaled to 50% in the print settings dialog.</p>
      </div>
      {% verbatim %}
      <div id="schedule">
        <table class="schedule" v-for="grouped_events in dates">
          <thead>
            <tr>
              <th colspan="4">{{ get_day_of_week(grouped_events[0]) }}</th>
            </tr>
          </thead>
          <template v-for="time in grouped_events[1]">
            <template v-for="events in time">
              <tr v-for="(event, index) in events">
                <td class="time" v-if="index === 0" :rowspan="events.length">{{ pretty_date(event.start_time) }}</td>
                <td class="description"><strong>{{ event.name }}</strong><br />{{ event.description }}</td>
                <td class="participants">
                  <p
                      v-for="participant in event.participants"
                      :class="'participant ' + (participant.is_moderator ? 'moderator' : '')"
                  >{{ participant.name }}</p>
                </td>
                <td class="room">{{ get_room_name(event) }}</td>
              </tr>
            </template>
          </template>
        </table>
      </div>
      {% endverbatim %}
    </div>
    <script defer type="text/javascript" src="{% static 'js/lib/raven.js' %}"></script>
    <script type="text/javascript">Raven.config('{% sentry_public_dsn %}').install()</script>
  </body>
</html>

website/templates/website/reports/tent_cards.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link href="{% static 'website/reports/tent_cards.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% for event in events %}
      {% for participant in event.participant_set.all %}
      <div class='tent'>
          <div class='back'>
            <div>
            <table>
              <tr>
                <td class="date">{{ event.start_time|date:"l" }}</td>
                <td class="participant">{{ participant.attendee.get_display_name }}</td>
              </tr>
              <tr>
                <td class="room">{{ event.room.name }}</td>
                <td class="name">{{ event.name }}</td>
              </tr>
              <tr>
                <td class="time">{{ event.start_time|date:"h:i A" }}</td>
                <td class="description">{{ event.description }}</td>
              </tr>
            </table>
            </div>
          </div>
          <div class='front'>
            <div>{{ participant.attendee.get_display_name }}</div>
          </div>
      </div>
      {% endfor %}
    {% endfor %}
  </body>
</html>